apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toss-auto
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  # 도메인이 정해지면 host와 tls 항목을 채우세요.
  rules: []
